# Generated by Django 3.1.1 on 2020-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
