# Generated by Django 3.1.1 on 2020-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200918_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
